version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb

networks:
  app-network:
    driver: bridge
